### ISSUE TITLE
Airs Time Display (midnight or mult. days) issue on front & indiv. prog pages from prog eps.

### ISSUE THREAD

**Issue by ghost** [kboofm/kboo.fm#28]
On some pages, with program episodes whose **time ends at midnight**, or whose **dates span multiple days**, text produced looks like this:

Airs at: Sat, 04/22/2017 at 5:30pm - Sun, 04/23/2017 at Sun, 04/23/2017
even as the settings on the individual prog ep edit page are correct.

"Normal" text is : Airs at: Sat, 04/22/2017 at 12:00pm - 2:00pm

This happens on the **front page** and on **individual program pages**

![kboo-fm-date-at-date-instead-of-time](https://cloud.githubusercontent.com/assets/578433/25297815/228cb514-26a5-11e7-93ea-b62f20cbf2ec.png)

![screen shot 2017-04-21 at 3 18 25 pm](https://cloud.githubusercontent.com/assets/578433/25297942/ecaebb76-26a5-11e7-8f83-5788ca097f13.png)

**Comment by beefman1** [comment]
See inner city blues festival in these lists.

http://xdev.kboo.fm/program/special-programming-music?page=2
http://xdev.kboo.fm/program/special-programming-music/content?page=2

**Comment by beefman1** [comment]
what is the url to the second screenshot above?  I don't see the double "A variety of music specials..." line anywhere.

**Comment by ghost** [comment]
>what is the url to the second screenshot above?

http://kboo.fm/program/special-programming-music

> I don't see the double "A variety of music specials..." line anywhere.

Either do I. Am I supposed to?

**Comment by beefman1** [comment]
It's in the second screenshot under the podcast line.

**Comment by ghost** [comment]
Yep, so noted. It's not on the live page now.

**Comment by troff** [comment]
seems that this is still an issue - see the screenshot attached.
it only affects the episodes that start before midnight,  but end at or after midnight. 

![screenshot_20170815-080803](https://user-images.githubusercontent.com/4783226/29322100-34697f3c-8191-11e7-99f6-5fa8a541ef6b.png)

**Comment by beefman1** [comment]
Can you post the URL?

It looks right here: http://kboo.fm/media/58932-tribute-philip-cohran-and-more

EDIT: nevermind i found it.

**Comment by beefman1** [comment]
i merged the changes from dev to live.

**Comment by troff** [comment]
seems that this is still an issue - see the screenshot attached.
it only affects the episodes that start before midnight,  but end at or after midnight. 

![screenshot_20170815-080803](https://user-images.githubusercontent.com/4783226/29322100-34697f3c-8191-11e7-99f6-5fa8a541ef6b.png)

it only appears incorrectly on the list pages which show titles and summaries. it appears correctly on the program episode page itself.

**Comment by beefman1** [comment]
That's the same screenshot.  You're here, right?  http://kboo.fm/program/special-programming-music

This is what i see.
![ss](https://user-images.githubusercontent.com/14895568/29392510-5216de58-82cc-11e7-8dbf-918d7d39c60e.png)

**Comment by troff** [comment]
fixed
